import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const cardsPath = resolve(here, '..', 'data', 'cards.json');
const outPath   = resolve(here, '..', 'db', 'seed.sql');

const cards = JSON.parse(readFileSync(cardsPath, 'utf8'));

function esc(v) {
  if (v === undefined || v === null) return 'null';
  if (typeof v === 'number') return String(v);
  if (Array.isArray(v)) {
    const inner = v.map(s => `'${String(s).replace(/'/g, "''")}'`).join(',');
    return `array[${inner}]::text[]`;
  }
  return `'${String(v).replace(/'/g, "''")}'`;
}

const rows = cards.map(c => {
  return `(${esc(c.id)}, ${esc(c.rarity)}, ${esc(c.type)}, ${esc(c.role)}, ${esc(c.name)}, ${esc(c.quote)}, ${esc(c.desc)}, ${esc(c.emoji)}, ${esc(c.destined_tags)}, ${esc(c.destined_roll)})`;
});

const sql = `-- Auto-generated by scripts/gen-seed.js. Do not edit by hand.
-- Run after db/schema.sql. Idempotent: re-running will upsert into cards.

insert into cards (id, rarity, type, role, name, quote, "desc", emoji, destined_tags, destined_roll) values
${rows.join(',\n')}
on conflict (id) do update set
  rarity        = excluded.rarity,
  type          = excluded.type,
  role          = excluded.role,
  name          = excluded.name,
  quote         = excluded.quote,
  "desc"        = excluded."desc",
  emoji         = excluded.emoji,
  destined_tags = excluded.destined_tags,
  destined_roll = excluded.destined_roll,
  updated_at    = now();
`;

writeFileSync(outPath, sql);
console.log(`Wrote ${cards.length} cards to ${outPath}`);
